/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppLmsLiveRouteImport } from './routes/app.lms.live'
import { Route as AppCrmPipelineRouteImport } from './routes/app.crm.pipeline'
import { Route as AppCrmLeadsRouteImport } from './routes/app.crm.leads'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLmsLiveRoute = AppLmsLiveRouteImport.update({
  id: '/lms/live',
  path: '/lms/live',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmPipelineRoute = AppCrmPipelineRouteImport.update({
  id: '/crm/pipeline',
  path: '/crm/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmLeadsRoute = AppCrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/crm/leads': typeof AppCrmLeadsRoute
  '/app/crm/pipeline': typeof AppCrmPipelineRoute
  '/app/lms/live': typeof AppLmsLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/crm/leads': typeof AppCrmLeadsRoute
  '/app/crm/pipeline': typeof AppCrmPipelineRoute
  '/app/lms/live': typeof AppLmsLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/crm/leads': typeof AppCrmLeadsRoute
  '/app/crm/pipeline': typeof AppCrmPipelineRoute
  '/app/lms/live': typeof AppLmsLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/crm/leads'
    | '/app/crm/pipeline'
    | '/app/lms/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/crm/leads'
    | '/app/crm/pipeline'
    | '/app/lms/live'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/crm/leads'
    | '/app/crm/pipeline'
    | '/app/lms/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lms/live': {
      id: '/app/lms/live'
      path: '/lms/live'
      fullPath: '/app/lms/live'
      preLoaderRoute: typeof AppLmsLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/pipeline': {
      id: '/app/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/app/crm/pipeline'
      preLoaderRoute: typeof AppCrmPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/leads': {
      id: '/app/crm/leads'
      path: '/crm/leads'
      fullPath: '/app/crm/leads'
      preLoaderRoute: typeof AppCrmLeadsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppCrmLeadsRoute: typeof AppCrmLeadsRoute
  AppCrmPipelineRoute: typeof AppCrmPipelineRoute
  AppLmsLiveRoute: typeof AppLmsLiveRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppCrmLeadsRoute: AppCrmLeadsRoute,
  AppCrmPipelineRoute: AppCrmPipelineRoute,
  AppLmsLiveRoute: AppLmsLiveRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
